server:
    port: 8081

spring:
    datasource:
        name: demo
        url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

        druid:
          #初始化大小，最小，最大
          initial-size: 5
          min-idle: 5
          max-active: 20
          #配置获取连接等待超时时间
          max-wait: 60000
          #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位为毫秒
          time-between-eviction-runs-millis: 6000
          #配置一个连接在池中的最小生存时间，单位是毫秒
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 1 FROM DUAL
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PsCache的大小
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          #配置监控统计拦截的filters,去掉后监控界面sql将无法统计，‘wall'用于防火墙
          filters: "stat,wall,log4j"
          #通过connectProperties 属性来打开mergerSql功能，慢sql功能
          connection-properties: druid.stat.mergeSql=true; druid.stat.showSqlMillis=5000



securityconfig:
  logoutsuccssurl: /
  permitall: /rest/**,/bbs**
  deniedpage: /deny
  urlroles: /**/new/** = admin;
    /**/edit/** = admin,editor;
    /**/delete/** = admin


logging:
    level:
        com.demo.mapper : debug




